from almalinux:latest
USER root
WORKDIR /app
RUN echo "Hi" > file.html && \
    yum install nginx -y
    rm -rf usr/share/nginx/html && \
    cp file.html usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]