FROM almalinux:latest
RUN adduser sha123 && \
    adduser -g wheel -s /bin/bash -c "adding sha123" -m -d /home/sha123 sha123
USER sha123
RUN sudo yum install nginx -y && \
    echo "HI" > \tmp\index.html && \
    rm -rf usr/share/nginx/html && \
    cp \tmp\index.html usr/share/nginx/html
CMD ["nginx", "-g" "daemon off;"]