FROM almalinux:latest
RUN adduser sha123
USER sha123
RUN yum install nginx -y && \
    echo "HI" > \tmp\index.html && \
    rm -rf usr/share/nginx/html && \
    cp \tmp\index.html usr/share/nginx/html
CMD ["nginx", "-g" "daemon off;"]